<a href="https://colab.research.google.com/github/frankmulungi/Coursera-Test/blob/master/projectpandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

# upload dataset
project = pd.read_csv('project_dataset.csv')

# now test run to return top 5

project.head(5)

,name,author,narrator,time,releasedate,language,stars,price
0,Geronimo Stilton #11 & #12,Writtenby:GeronimoStilton,Narratedby:BillLobely,2 hrs and 20 mins,04-08-08,English,5 out of 5 stars34 ratings,468.00
1,The Burning Maze,Writtenby:RickRiordan,Narratedby:RobbieDaymond,13 hrs and 8 mins,01-05-18,English,4.5 out of 5 stars41 ratings,820.00
2,The Deep End,Writtenby:JeffKinney,Narratedby:DanRussell,2 hrs and 3 mins,06-11-20,English,4.5 out of 5 stars38 ratings,410.00
3,Daughter of the Deep,Writtenby:RickRiordan,Narratedby:SoneelaNankani,11 hrs and 16 mins,05-10-21,English,4.5 out of 5 stars12 ratings,615.00
4,"The Lightning Thief: Percy Jackson, Book 1",Writtenby:RickRiordan,Narratedby:JesseBernstein,10 hrs,13-01-10,English,4.5 out of 5 stars181 ratings,820.00

In [2]:
# this returns the bottom 5 data in the csv file

project.tail(5)

,name,author,narrator,time,releasedate,language,stars,price
87484,Last Days of the Bus Club,Writtenby:ChrisStewart,Narratedby:ChrisStewart,7 hrs and 34 mins,09-03-17,English,Not rated yet,596.00
87485,The Alps,Writtenby:StephenO'Shea,Narratedby:RobertFass,10 hrs and 7 mins,21-02-17,English,Not rated yet,820.00
87486,The Innocents Abroad,Writtenby:MarkTwain,Narratedby:FloGibson,19 hrs and 4 mins,30-12-16,English,Not rated yet,938.00
87487,A Sentimental Journey,Writtenby:LaurenceSterne,Narratedby:AntonLesser,4 hrs and 8 mins,23-02-11,English,Not rated yet,680.00
87488,Havana,Writtenby:MarkKurlansky,Narratedby:FleetCooper,6 hrs and 1 min,07-03-17,English,Not rated yet,569.00

In [3]:
# showing one column

project['author']

0        Writtenby:GeronimoStilton
1            Writtenby:RickRiordan
2             Writtenby:JeffKinney
3            Writtenby:RickRiordan
4            Writtenby:RickRiordan
                   ...
87484       Writtenby:ChrisStewart
87485      Writtenby:StephenO'Shea
87486          Writtenby:MarkTwain
87487     Writtenby:LaurenceSterne
87488      Writtenby:MarkKurlansky
Name: author, Length: 87489, dtype: object

In [4]:
# removing writtenby from column

project['author'] = project['author'].str.replace('Writtenby:', '')

In [5]:
# check to see that it's gone

project['author']

0        GeronimoStilton
1            RickRiordan
2             JeffKinney
3            RickRiordan
4            RickRiordan
              ...
87484       ChrisStewart
87485      StephenO'Shea
87486          MarkTwain
87487     LaurenceSterne
87488      MarkKurlansky
Name: author, Length: 87489, dtype: object

In [6]:
# add space to first and surname
project['author'] = project['author'].str.split(r'(?=[A-Z])').str.join(' ')

In [7]:
# now test it out to see that it's worked
project['author']

0         Geronimo Stilton
1             Rick Riordan
2              Jeff Kinney
3             Rick Riordan
4             Rick Riordan
               ...
87484        Chris Stewart
87485      Stephen O' Shea
87486           Mark Twain
87487      Laurence Sterne
87488       Mark Kurlansky
Name: author, Length: 87489, dtype: object

In [8]:
# show narrator column
project['narrator']

0            Narratedby:BillLobely
1         Narratedby:RobbieDaymond
2            Narratedby:DanRussell
3        Narratedby:SoneelaNankani
4        Narratedby:JesseBernstein
                   ...
87484      Narratedby:ChrisStewart
87485        Narratedby:RobertFass
87486         Narratedby:FloGibson
87487       Narratedby:AntonLesser
87488       Narratedby:FleetCooper
Name: narrator, Length: 87489, dtype: object

In [11]:
# clean narrator column as I did the author column

project['narrator'] = project['narrator'].str.replace('Narratedby:', '')

project['narrator'] = project['narrator'].str.split(r'(?=[A-Z])').str.join(' ')

In [12]:
# test output after previous steps
project['narrator']

0             Bill Lobely
1          Robbie Daymond
2             Dan Russell
3         Soneela Nankani
4         Jesse Bernstein
               ...
87484       Chris Stewart
87485         Robert Fass
87486          Flo Gibson
87487        Anton Lesser
87488        Fleet Cooper
Name: narrator, Length: 87489, dtype: object

In [13]:
project = project

,name,author,narrator,time,releasedate,language,stars,price
0,Geronimo Stilton #11 & #12,Geronimo Stilton,Bill Lobely,2 hrs and 20 mins,04-08-08,English,5 out of 5 stars34 ratings,468.00
1,The Burning Maze,Rick Riordan,Robbie Daymond,13 hrs and 8 mins,01-05-18,English,4.5 out of 5 stars41 ratings,820.00
2,The Deep End,Jeff Kinney,Dan Russell,2 hrs and 3 mins,06-11-20,English,4.5 out of 5 stars38 ratings,410.00
3,Daughter of the Deep,Rick Riordan,Soneela Nankani,11 hrs and 16 mins,05-10-21,English,4.5 out of 5 stars12 ratings,615.00
4,"The Lightning Thief: Percy Jackson, Book 1",Rick Riordan,Jesse Bernstein,10 hrs,13-01-10,English,4.5 out of 5 stars181 ratings,820.00